## This is test deployment for Kubernetes platforms.
## This is not intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-acmesolver
  name: test-acmesolver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-acmesolver
  template:
    metadata:
      labels:
        app: test-acmesolver
    spec:
      containers:
      - image: bitnami/acmesolver
        name: acmesolver
